### get available apartments
GET http://localhost:8080/apartment/available/2024-01-01/2024-12-31

### create a new booking
POST http://localhost:8080/booking/create
Content-Type: application/json

{
  "customer_id": 1,
  "apartments": [
    {
      "apartment_id": 1,
      "date_from": "2024-01-01",
      "date_to": "2023-01-04"
    }
  ],
  "packages": []
}

### create a new booking
POST http://localhost:8080/booking/create
Content-Type: application/json

{
  "customer_id": 1,
  "apartments": [
    {
      "apartment_id": 1,
      "date_from": "2024-02-01",
      "date_to": "2023-02-04"
    },
    {
      "apartment_id": 1,
      "date_from": "2024-02-01",
      "date_to": "2023-02-04"
    }
  ],
  "packages": []
}

### complete with your requests